export const films = [
  {
    id: "hero",
    title: "Hero",
    original: "英雄",
    year: 2002,
    place: "China",
    director: "Zhang Yimou",
    style: "Wuxia",
    theme: "Poetry in motion",
    accent: "#EF714B",
    image: "hero-poster.png",
    poster: "hero-poster.png",
    position: "50% 48%",
    alt: "Hero poster with Jet Li and Maggie Cheung in front of a field of spears.",
    traits: ["Grace", "Imagination", "Philosophy"],
    result:
      "You see a fight as something closer to poetry. You are drawn to impossible movement, striking images, and the ideas that linger after the action ends.",
    storyTitle: "When a sword becomes a brush.",
    story: [
      "In Hero, a fight can feel like a painting coming to life. Color, movement, and shifting versions of a story make each confrontation more than a contest of strength.",
      "Wuxia belongs to a world of martial chivalry, romance, and imagination with deep literary roots. The film brings that world to the screen through questions of power, sacrifice, and what it means to act for something beyond yourself.",
      "Watch how the colors change. What happens to your understanding of the characters when the same story is told differently?",
    ],
    trailer: "https://www.youtube.com/watch?v=MgsddFEe9Oc",
    trailerSource: "Miramax · YouTube",
    source: "https://www.bfi.org.uk/lists/10-great-wuxia-swordplay-films",
    sourceName: "BFI · On wuxia and Hero",
    credit: "Poster sourced from Miramax.",
    creditUrl: "https://www.miramax.com/movie/hero-ying-xiong/",
  },
  {
    id: "ip-man",
    title: "Ip Man",
    original: "葉問",
    year: 2008,
    place: "Hong Kong",
    director: "Wilson Yip",
    style: "Wing Chun",
    theme: "Strength in restraint",
    accent: "#BCD0B1",
    image: "ipman-still.jpg",
    poster: "ipman-poster.jpg",
    position: "49% 50%",
    alt: "Donnie Yen as Ip Man holding a staff in a dimly lit industrial interior.",
    traits: ["Precision", "Discipline", "Dignity"],
    result:
      "You are drawn to the quiet confidence of someone who knows exactly when to move. Precision and restraint matter to you as much as the impact of a strike.",
    storyTitle: "The power of holding your ground.",
    story: [
      "Donnie Yen’s Ip Man makes control compelling. The film places its Wing Chun practitioner in a world disrupted by war, where the meaning of standing your ground reaches beyond a single opponent.",
      "Through its dramatized portrait of a martial artist, the film connects technique with dignity, community, and identity. Read the action as a way of expressing those concerns, rather than treating every screen event as historical fact.",
      "Look at the contrast between stillness and movement. How does restraint change the way you read a moment of force?",
    ],
    trailer: "https://www.youtube.com/watch?v=wv9PD1_JIC8",
    trailerSource: "Well Go USA · YouTube",
    source: "https://wellgousa.com/films/ip-man",
    sourceName: "Well Go USA · Film context",
    credit: "Promotional imagery sourced from Well Go USA Entertainment.",
    creditUrl: "https://wellgousa.com/films/ip-man",
  },
  {
    id: "the-rebel",
    title: "The Rebel",
    original: "Dòng máu anh hùng",
    year: 2007,
    place: "Vietnam",
    director: "Charlie Nguyễn",
    style: "Vovinam",
    theme: "Movement as resistance",
    accent: "#87CEC7",
    image: "rebel-backdrop.webp",
    poster: "rebel-poster.jpg",
    position: "52% 50%",
    alt: "Johnny Trí Nguyễn and Ngô Thanh Vân in a warm-toned still from The Rebel.",
    traits: ["Adaptability", "Conviction", "Resistance"],
    result:
      "You respond to quick thinking and movement that refuses to be contained. The Rebel turns that restless energy toward questions of belonging, conscience, and resistance.",
    storyTitle: "Which side will you stand on?",
    story: [
      "Set in 1920s Vietnam under French colonial rule, The Rebel follows a man whose work for the colonial government comes into conflict with his conscience. Meeting a resistance fighter makes that conflict personal.",
      "The action becomes a way to explore allegiance: who you serve, what you believe, and what it costs to change sides. This festival pairs the film with Vovinam as a doorway into Vietnamese screen combat, rather than a claim that every technique is a historical demonstration.",
      "Watch for the moments when movement changes a relationship. Who is protecting whom, and how does that shift?",
    ],
    trailer:
      "https://tv.apple.com/us/clip/the-rebel/umc.cmc.4jhgbuxv2uejlt8r97g0uluqq?targetId=umc.cmc.6zkvq0xvguupz9mn560re1b9m&targetType=Movie",
    trailerSource: "Apple TV · Official trailer",
    source:
      "https://danaff.vn/phim-du-thi/dien-anh-viet-nam-40-nam-doi-moi-id13/dong-mau-anh-hung-id259",
    sourceName: "Da Nang Asian Film Festival · Film context",
    credit:
      "Film imagery sourced from Da Nang Asian Film Festival. Trailer via Apple TV / Lionsgate.",
    creditUrl:
      "https://danaff.vn/phim-du-thi/dien-anh-viet-nam-40-nam-doi-moi-id13/dong-mau-anh-hung-id259",
  },
  {
    id: "the-protector",
    title: "The Protector",
    original: "ต้มยำกุ้ง",
    year: 2005,
    place: "Thailand",
    director: "Prachya Pinkaew",
    style: "Muay Thai",
    styleDetail: "Muay Thai / Muay Boran",
    theme: "Power with a purpose",
    accent: "#EDBA69",
    image: "protector-backdrop.jpg",
    poster: "protector-poster.jpg",
    position: "35% 50%",
    alt: "Tony Jaa kneeling with two long weapons in a red-lit interior in The Protector.",
    traits: ["Intensity", "Commitment", "Heritage"],
    result:
      "You are drawn to raw power, physical intensity, and relentless movement. Discover how Muay Thai becomes more than spectacle — carrying Thai identity, heritage, and national pride.",
    storyTitle: "What would you fight to protect?",
    story: [
      "The Protector sends Kham far from home in pursuit of two stolen elephants. Tony Jaa’s physical commitment gives the rescue its urgency, but the story’s emotional force comes from a bond that is treated as family.",
      "Director Prachya Pinkaew connects the film to Thai cultural traditions and the relationship between people and elephants. Through this lens, its Muay Thai-inspired action expresses attachment, responsibility, and the fear of losing something irreplaceable.",
      "Look beyond the impact of a stunt. What does Kham’s determination tell you about what he values?",
    ],
    trailer: "https://www.youtube.com/watch?v=4Pev6lkexo8",
    trailerSource: "Sahamongkolfilm · YouTube",
    source:
      "https://sahamongkolfilm.com/saha-movie/tom-yum-goong-protector-2548",
    sourceName: "Sahamongkolfilm · Director’s perspective",
    credit: "Promotional imagery sourced from Sahamongkolfilm International.",
    creditUrl:
      "https://sahamongkolfilm.com/saha-movie/tom-yum-goong-protector-2548",
  },
  {
    id: "13-assassins",
    title: "13 Assassins",
    original: "十三人の刺客",
    year: 2010,
    place: "Japan",
    director: "Takashi Miike",
    style: "Samurai",
    styleDetail: "Samurai sword fighting",
    theme: "Honour under pressure",
    accent: "#BDC9E1",
    image: "assassins-still4.jpg",
    poster: "assassins-still2.jpg",
    position: "49% 48%",
    alt: "A group of samurai standing together in a village in 13 Assassins.",
    traits: ["Strategy", "Loyalty", "Resolve"],
    result:
      "You are drawn to a plan, a shared purpose, and the resolve to see it through. For you, the most powerful confrontation is one where every choice carries a consequence.",
    storyTitle: "When loyalty means taking a stand.",
    story: [
      "Near the end of Japan’s feudal era, a group of samurai is recruited to stop a violent lord. Takashi Miike’s film puts an uncomfortable question at the center of its action: what does duty mean when authority becomes destructive?",
      "The group’s planning and collective resolve let us read sword fighting through the tension between obedience and responsibility. Honour is something tested by a decision, rather than simply announced by a title.",
      "Watch how individual gestures become a shared effort. What changes when a fight is about everyone making it count?",
    ],
    trailer: "https://www.youtube.com/watch?v=Xpm007vne54",
    trailerSource: "Magnet Releasing · YouTube",
    source: "https://www.magnetreleasing.com/13assassins/",
    sourceName: "Magnet Releasing · Film context",
    credit: "Photo courtesy of Magnet Releasing.",
    creditUrl: "https://www.magnoliapictures.com/13assassins-press-kit",
  },
];
